### ISSUE TITLE
중간 발표 피드백

### ISSUE THREAD

**Issue by kangminjun2024** [pkg0203/SSAP#1]
1. git에 읽을거리가 좀 부족한 느낌 readme를 더 채워주면 좋을것같음
2. 현 기간에 어디에 초점을 맞추고 있는지 얘기하고 있어서 좋음
3. 발표 자료가 간단하지만 명료해서 강렬한 느낌, black/white와 키워드만 띄워놓고 
    발표자가 내용을 채우는 방법은 요즘 대기업 발표 컨셉
4. 프로젝트의 목적에 대해 얘기해주는 것 좋음
5. 발표 자료에 수치가 나타나는 통계 자료가 있는 것은 프로젝트 필요에 신뢰성을 더해줌 매우 칭찬
6. 코드 리뷰를 꾸준히 하면서 팀 전체가 성장하는 방향을 추구하는 것도 매우 칭찬함
7. 이후 일정에 대해 얘기해주면 더 좋을것같음
8. 전체적으로 잘하셨고 아직은 보이는 결과물이 없기에 최종 때 더 기대되는 부분이 있음

**Comment by pkg0203** [comment]
감사합니다! :)
